### PR TITLE
Update MozillaBuildSetup3.4 setup and signing manifest

### PR DESCRIPTION
**Pull request by escapewindow**
#61, but with a Google Drive link, less LFS, and more taskcluster CI.

### CODE REVIEW

**Comment by escapewindow** [comment]
@mitchhentges this doesn't look great:

```
[task 2021-11-16T21:17:38.604Z] __main__.IntegrityError: size mismatch on https://drive.google.com/file/d/1XWHvKlCkp-1-pSena9ITsspeExoMM4HH/view?usp=sharing: wanted 123131269; got 66148
```

**Comment by mitchhentges** [comment]
Oof, I bet it's looking at the Google-rendered "download" page, not the real exe.
I'll host it on my personal site and link that :)

Try specifying [`https://fuzzlesoft.ca/MozillaBuildSetup3.4.exe`](https://fuzzlesoft.ca/MozillaBuildSetup3.4.exe) as the URL.

**Comment by escapewindow** [comment]
Nice :) once we merge and *that* fetch task goes green, you can remove the file from your site if preferred.

**Review by jmaher — APPROVED** [review]
I like simpler reviews.

**Comment by mitchhentges** [comment]
Should we remove the first commit from this stack so that we don't merge the unused, fat file into the main repo's LFS?
(I don't know how LFS works, maybe we already incurred the cost due to the PR, unsure 😅 )

**Comment by escapewindow** [comment]
Squashed, so the LFS file is nuked.
And yeah, we've already incurred the LFS bandwidth costs (free, but maxed out our limited free tier bandwidth).

**Pull request merged**
