### PR TITLE
Bug 1873639 - Sign channel-switching MARs for Thunderbird 115 monthly releases

### PR DESCRIPTION
**Pull request by dandarnell**
New MARs for Thunderbird are unfortunately needed, as infra changes weren't ready before Thunderbird 115.8.1 released. These are new MARs for 115.8.1 instead of 115.8.0.

### CODE REVIEW

**Comment by jcristau** [comment]
This is kind of why I suggested versioning them as 116.0 last time around...

**Review by jcristau — CHANGES_REQUESTED** [review]
Please make the version in the mar metadata 116.0, or at least 115.9.0, so we don't have to keep doing this.

**Comment by jcristau** [comment]
The constraint is that the version number in the mar must be at least MOZ_APP_VERSION (https://searchfox.org/mozilla-central/rev/172e503b01303c153b0dfe39827acb2bc9ede1b9/toolkit/mozapps/update/updater/archivereader.cpp#155-170) for the updater to accept it.
For normal mar files, the product version in the mar header is the version of the actual application in the archive, but when channel-switching we're not actually touching the application version, so the version we pick for the header is arbitrary.

**Comment by dandarnell** [comment]
All three 116.0 dep-signed MARs have now been tested and should be ready to merge.

**Review by jcristau — APPROVED** [review]

**Pull request merged**
