### PR TITLE
Update MozillaBuildSetup3.4 setup and signing manifest

### PR DESCRIPTION
**Pull request by mitchhentges**
I erroneously built the previous setup off too new of a revision, so it prematurely removes nsis and mozmake.
This one is correctly built from `MOZILLABUILD_3_4_0_RELEASE`

### CODE REVIEW

**Comment by mitchhentges** [comment]
Actually, give me a bit here, I'm running into local surprises around Python 3, let me make sure they're unrelated to the the changes in 3.4.

**Comment by mitchhentges** [comment]
Yep, was an issue with leftover state from an upcoming release, but not a problem with 3.4. Reopening.

**Comment by escapewindow** [comment]
We've blown past our LFS quota, so it's quite likely this will fail. Do we have another place to serve this file from?

**Comment by mitchhentges** [comment]
Hmm, it depends on the requirements.
If it just needs to be hosted long enough to sign, then [perhaps my Google Drive link is sufficient](https://drive.google.com/file/d/1XWHvKlCkp-1-pSena9ITsspeExoMM4HH/view?usp=sharing).
If not, I _can_ chuck it up on S3 as `MozillaBuild3.4-unsigned.exe`, but I'd rather not clutter up the bucket if possible.

How have we worked around LFS quotas in the past?

**Comment by escapewindow** [comment]
> Hmm, it depends on the requirements. If it just needs to be hosted long enough to sign, then [perhaps my Google Drive link is sufficient](https://drive.google.com/file/d/1XWHvKlCkp-1-pSena9ITsspeExoMM4HH/view?usp=sharing).

Can taskcluster download that file without auth?

> If not, I _can_ chuck it up on S3 as `MozillaBuild3.4-unsigned.exe`, but I'd rather not clutter up the bucket if possible.

This may be our best option.
 
> How have we worked around LFS quotas in the past?

We haven't had >100mb files to adhoc-sign in the past.

**Comment by mitchhentges** [comment]
> Can taskcluster download that file without auth?

Yep! I've just dropped the authentication requirement from the link.

**Comment by escapewindow** [comment]
> > Can taskcluster download that file without auth?
> 
> Yep! I've just dropped the authentication requirement from the link.

works for me.

**Comment by escapewindow** [comment]
Fixed in #62.

**Pull request closed without merging**
