### PR TITLE
Bump taskgraph to v7.x

### PR DESCRIPTION
**Pull request by JohanLorenzo**
The main driver for this is [bug 1868558](https://bugzilla.mozilla.org/show_bug.cgi?id=1868558). I just need to get a new decision task to rebuild cached tasks. I seized this opportunity to bump taskgraph.

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
The failed tasks are caused by expired artifacts. I don't think they're related to these changes.

**Comment by ahal** [comment]
> The failed tasks are caused by expired artifacts. I don't think they're related to these changes.

We should probably remove them in that case, but we can do that in a differnet PR.

**Review by ahal — APPROVED** [review]
Thanks, lgtm!

**Comment by JohanLorenzo** [comment]
> We should probably remove them in that case, but we can do that in a differnet PR.

Agreed. Done in this PR so I could green it up.

**Pull request merged**
